import pandas as pd


if __name__ == "__main__":
    dict1 = {
        "hotel_group_id": 2,
        "hotel_id": 9,
        "name": "test001",
        "phone": "13912345678",
        "mobile": "13912345678",
        "fax": "13912345678",
        "email": "",
        "website": "",
        "blog": "",
        "linkman1": "ZS02",
        "occupation": "",
        "linkman2": "",
        "country": "CN",
        "state": "",
        "city": "",
        "division": "",
        "street": " test001",
        "zipcode": "",
        "representative": "",
        "register_no": "",
        "bank_name": "",
        "bank_account": "",
        "tax_no": "",
        "remark": "",
        "sys_cat": "C",
        "ratecode": "",
        "saleman": "",
    }
    dict2 = {
        "hotel_group_id": 2,
        "hotel_id": 9,
        "name": "test002",
        "phone": "13912345678",
        "mobile": "13912345678",
        "fax": "13912345678",
        "email": "",
        "website": "",
        "blog": "",
        "linkman1": "ZS02",
        "occupation": "",
        "linkman2": "",
        "country": "CN",
        "state": "",
        "city": "",
        "division": "",
        "street": " test002",
        "zipcode": "",
        "representative": "",
        "register_no": "",
        "bank_name": "",
        "bank_account": "",
        "tax_no": "",
        "remark": "",
        "sys_cat": "C",
        "ratecode": "",
        "saleman": "",
    }

    test = pd.DataFrame(dict1, dict2, index=[0, 1])
    print(test)
